# Generated by Django 4.0.4 on 2022-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('first_name', models.CharField(blank=True, db_index=True, default='Guest', max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, default='Guest', max_length=120, null=True)),
            ],
        ),
    ]
